import React from 'react';
import {
  CheckCircle as CheckCircleIcon,
  Error as ErrorIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  Cancel as CancelIcon,
  ArrowBack as ArrowBackIcon,
  ArrowForward as ArrowForwardIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Save as SaveIcon,
  Print as PrintIcon,
  Search as SearchIcon,
  FilterList as FilterListIcon,
  Settings as SettingsIcon,
  Menu as MenuIcon,
  Close as CloseIcon,
  MoreVert as MoreVertIcon,
  Refresh as RefreshIcon,
  CloudUpload as CloudUploadIcon,
  CloudDownload as CloudDownloadIcon,
  Person as PersonIcon,
  Lock as LockIcon,
  LockOpen as LockOpenIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
} from '@mui/icons-material';

const IconSet = {
  CheckCircle: CheckCircleIcon,
  Error: ErrorIcon,
  Warning: WarningIcon,
  Info: InfoIcon,
  Cancel: CancelIcon,
  ArrowBack: ArrowBackIcon,
  ArrowForward: ArrowForwardIcon,
  Add: AddIcon,
  Edit: EditIcon,
  Delete: DeleteIcon,
  Save: SaveIcon,
  Print: PrintIcon,
  Search: SearchIcon,
  FilterList: FilterListIcon,
  Settings: SettingsIcon,
  Menu: MenuIcon,
  Close: CloseIcon,
  MoreVert: MoreVertIcon,
  Refresh: RefreshIcon,
  CloudUpload: CloudUploadIcon,
  CloudDownload: CloudDownloadIcon,
  Person: PersonIcon,
  Lock: LockIcon,
  LockOpen: LockOpenIcon,
  Visibility: VisibilityIcon,
  VisibilityOff: VisibilityOffIcon,
};

export default IconSet; 